
CONSOLE_ENABLE = no
VIA_ENABLE = no
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes

MOUSEKEY_ENABLE = no # Mouse keys
EXTRAKEY_ENABLE = yes # Audio control and System controls
SPLIT_KEYBOARD = yes

COMBO_ENABLE = yes
TAP_DANCE_ENABLE = yes
UNICODEMAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
SEND_STRING_ENABLE = yes
